version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"