# syntax=docker/dockerfile:1.7

FROM --platform=$BUILDPLATFORM golang:1.26-trixie@sha256:b75d466dd608587fd66cca705a307ba65b889827d06ad61d6a75f0482b51b7c7 AS builder

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT=""
ARG LDFLAGS

ENV CGO_ENABLED=0 \
    GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH} \
    GOARM=${TARGETVARIANT}

WORKDIR /go/src/github.com/open-policy-agent
COPY . gatekeeper.runtime
COPY --from=frameworks . frameworks.runtime

WORKDIR /go/src/github.com/open-policy-agent/gatekeeper.runtime
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    test "$(go env GOWORK)" = "/go/src/github.com/open-policy-agent/gatekeeper.runtime/go.work" \
    && test "$(go list -m -f '{{.Dir}}' github.com/open-policy-agent/frameworks/constraint)" = "/go/src/github.com/open-policy-agent/frameworks.runtime/constraint" \
    && go build -trimpath -ldflags "${LDFLAGS}" -o /manager

FROM gcr.io/distroless/static-debian12@sha256:6447365a6337c3732f412d1b74357b30a633831955b2bc45552b0086be907687

COPY --from=builder /manager /manager
USER 65532:65532
ENTRYPOINT ["/manager"]
