replicas: 1
auditInterval: 60
constraintViolationsLimit: 20
auditFromCache: false
logLevel: INFO
image:
  repository: quay.io/sozercan/gatekeeper
  release: v4.0.0
  pullPolicy: IfNotPresent
nodeSelector: {}
tolerations: []
podAnnotations: {}
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
