name: load_test
on: [push, pull_request]
# on:
#   issue_comment:
#     types: [created]

jobs:
  # trigger:
  #   name: Trigger load test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: khan/pull-request-comment-trigger@1.0.0
  #       id: check
  #       with:
  #         trigger: '/runLoadTest'
  #         reaction: rocket
  #       env:
  #         GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  load_test:
    name: "Load test"
    runs-on: ubuntu-latest
    # needs: trigger
    timeout-minutes: 30
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Checkout clusterloader2
        run: |
          git clone https://github.com/kubernetes/perf-tests.git

      - name: Bootstrap e2e
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          make e2e-bootstrap

      - name: Deploy Gatekeeper
        run: |
          make e2e-build-load-image IMG=gatekeeper-e2e:latest
          make deploy IMG=gatekeeper-e2e:latest USE_LOCAL_IMG=true

      - name: Deploy policies
        run: |
          ./test/load/deploy-policies.sh
        env:
          NUMBER_TEMPLATES: 5
          NUMBER_CONSTRAINTS: 5
          POD_COUNT: 10
          POD_THROUGHPUT: 5
          WAIT_TIME: 1m

      - name: Run load tests
        run: |
          ./run-e2e.sh cluster-loader2 \
            --nodes=1 \
            --provider=local \
            --report-dir="$GITHUB_WORKSPACE/_artifacts" \
            --testconfig="$GITHUB_WORKSPACE/test/load/config-template.yaml"
        working-directory: perf-tests

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: load_test_results
          path: |
            _artifacts/*.json

      # - name: Comment results on PR
      #   env:
      #     URL: ${{ github.event.issue.comments_url }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     echo "Scale [run](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) results:" > comment.txt
      #     echo "\`\`\`" >> comment.txt
      #     cat ./tests/scale/testResults/results.txt >> comment.txt
      #     echo "\`\`\`" >> comment.txt
      #     echo "{ \"body\" : $(cat comment.txt | jq -sR)}" > proto.json
      #     curl \
      #       -X POST \
      #       $URL \
      #       -H "Content-Type: text/json" \
      #       -H "Authorization: token $GITHUB_TOKEN" \
      #       -d @proto.json