name: "pre-release"

on:
  push:
    branches:
      - "e2e-actions" # master

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: make docker-push-dev
        run: |
          make docker-login
          make docker-build IMG=gatekeeper:${GITHUB_SHA::8} DEV_TAG=${GITHUB_SHA::8}
          make docker-push-dev IMG=gatekeeper:${GITHUB_SHA::8} DEV_TAG=${GITHUB_SHA::8}
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
