name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/tags/}

      - name: m66ake docker-push-release
        run: |
          make docker-build IMG=gatekeeper:${VERSION}
          make docker-push-release IMG=gatekeeper:${VERSION}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
